"""Shared Qt StyleSheet helpers.

The global stylesheet generated by config.stylesheet covers QTableWidget and
QLineEdit, so per-widget overrides are no longer needed.
"""


def apply_table_style(table) -> None:
    """No-op — table styling is handled by the global stylesheet."""
    pass


def apply_search_style(widget) -> None:
    """No-op — input styling is handled by the global stylesheet."""
    pass
